name: Test Vector Equivalence

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: cmake -S . -B ./build
    - name: build
      run: cmake --build ./build
    - name: test
      run: ./build/aes
